name: Angular CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # 22 est encore instable pour Angular

      - name: Installer les dépendances
        run: npm install

      - name: Construire l'application Angular
        run: npm run build -- --configuration production

      - name: Déployer sur GitHub Pages
        run: |
          npx angular-cli-ghpages --dir=dist/portfolio --no-silent
