name: Angular CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Installer les dépendances
        run: npm install

      - name: Lancer les tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Construire l'application
        run: npm run build -- --configuration=production

      - name: Déployer sur GitHub Pages
        if: success()
        run: |
          npx angular-cli-ghpages --dir=dist/portfolio
