name: Angular CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installer les dépendances
        run: npm install

      - name: Construire l'application Angular
        run: npm run build -- --configuration production

      - name: Configurer l'identité Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

      - name: Déployer sur GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx angular-cli-ghpages --dir=dist/portfolio --repo=https://x-access-token:${GH_TOKEN}@github.com/HanaeNejjari/portfolio.git --no-silent

  
